### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [agoldberga/addressable-gtm-template#1]
https://github.com/agoldberga/addressable-gtm-template/blob/f3fc5696afd35019540dc258d0b2727aa1b60c1a/template.tpl#L104C67-L104C81

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by addressableid** [comment]
Fixed
